name: cross_channel
description: High-performance & flexible channels for Dart/Flutter.
version: 0.10.0
repository: https://github.com/mkidv/cross_channel
issue_tracker: https://github.com/mkidv/cross_channel/issues

topics:
  - concurrency
  - async
  - channels
  - mpsc
  - mpmc

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.30.0
